[build]
  # Build settings
  publish = "."
  command = "echo 'Static site - no build needed'"

[build.environment]
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://identity.netlify.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self' https:;
      frame-src https://identity.netlify.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    '''

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# Admin protection
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

# Redirects
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

# Force HTTPS
[[redirects]]
  from = "http://hydraulic-platform.netlify.app/*"
  to = "https://hydraulic-platform.netlify.app/:splat"
  status = 301
  force = true

# Arabic language redirects (if needed)
[[redirects]]
  from = "/ar/*"
  to = "/:splat"
  status = 301

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions (for future use)
[functions]
  directory = "netlify/functions"

# Edge functions (for future use)
[[edge_functions]]
  function = "geolocation"
  path = "/api/location"

# Plugin configuration
[[plugins]]
  package = "netlify-plugin-minify-html"
  [plugins.inputs]
    contexts = ["production"]

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    buildDir = "."
    exclude = ["/admin/**", "/_data/**"]

# Form handling (for future contact forms)
[forms]
  settings = true

# Identity settings for CMS
[template.environment]
  NETLIFY_CMS_MANUAL_INIT = "true"

# Dev server settings
[dev]
  framework = "#static"
  targetPort = 8080
  port = 8888
  autoLaunch = false

# Context-specific settings
[context.production]
  command = "echo 'Production build complete'"

[context.deploy-preview]
  command = "echo 'Deploy preview ready'"

[context.branch-deploy]
  command = "echo 'Branch deploy ready'"

# Large Media (if needed for images)
[lfs]
  enabled = false